# Generated by Django 5.0.3 on 2024-03-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('instruction', models.CharField(max_length=255)),
                ('target_muscles', models.CharField(max_length=150)),
                ('rest_between_sets', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
            },
        ),
    ]
