# Generated by Django 5.0.3 on 2024-03-13 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_exercisestatus_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisestatus',
            options={'verbose_name': 'Exercise status', 'verbose_name_plural': 'Status of exercises'},
        ),
        migrations.RemoveField(
            model_name='exercisestatus',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exercisestatus',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.exercises'),
        ),
    ]
